# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aightech/.gazebo/models/stewart_platform

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aightech/.gazebo/models/stewart_platform

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aightech/.gazebo/models/stewart_platform/CMakeFiles /home/aightech/.gazebo/models/stewart_platform/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aightech/.gazebo/models/stewart_platform/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stewart_platform

# Build rule for target.
stewart_platform: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stewart_platform
.PHONY : stewart_platform

# fast build rule for target.
stewart_platform/fast:
	$(MAKE) -f CMakeFiles/stewart_platform.dir/build.make CMakeFiles/stewart_platform.dir/build
.PHONY : stewart_platform/fast

src/joystick.o: src/joystick.cpp.o

.PHONY : src/joystick.o

# target to build an object file
src/joystick.cpp.o:
	$(MAKE) -f CMakeFiles/stewart_platform.dir/build.make CMakeFiles/stewart_platform.dir/src/joystick.cpp.o
.PHONY : src/joystick.cpp.o

src/joystick.i: src/joystick.cpp.i

.PHONY : src/joystick.i

# target to preprocess a source file
src/joystick.cpp.i:
	$(MAKE) -f CMakeFiles/stewart_platform.dir/build.make CMakeFiles/stewart_platform.dir/src/joystick.cpp.i
.PHONY : src/joystick.cpp.i

src/joystick.s: src/joystick.cpp.s

.PHONY : src/joystick.s

# target to generate assembly for a file
src/joystick.cpp.s:
	$(MAKE) -f CMakeFiles/stewart_platform.dir/build.make CMakeFiles/stewart_platform.dir/src/joystick.cpp.s
.PHONY : src/joystick.cpp.s

src/pos.o: src/pos.cpp.o

.PHONY : src/pos.o

# target to build an object file
src/pos.cpp.o:
	$(MAKE) -f CMakeFiles/stewart_platform.dir/build.make CMakeFiles/stewart_platform.dir/src/pos.cpp.o
.PHONY : src/pos.cpp.o

src/pos.i: src/pos.cpp.i

.PHONY : src/pos.i

# target to preprocess a source file
src/pos.cpp.i:
	$(MAKE) -f CMakeFiles/stewart_platform.dir/build.make CMakeFiles/stewart_platform.dir/src/pos.cpp.i
.PHONY : src/pos.cpp.i

src/pos.s: src/pos.cpp.s

.PHONY : src/pos.s

# target to generate assembly for a file
src/pos.cpp.s:
	$(MAKE) -f CMakeFiles/stewart_platform.dir/build.make CMakeFiles/stewart_platform.dir/src/pos.cpp.s
.PHONY : src/pos.cpp.s

src/stewart_platform.o: src/stewart_platform.cpp.o

.PHONY : src/stewart_platform.o

# target to build an object file
src/stewart_platform.cpp.o:
	$(MAKE) -f CMakeFiles/stewart_platform.dir/build.make CMakeFiles/stewart_platform.dir/src/stewart_platform.cpp.o
.PHONY : src/stewart_platform.cpp.o

src/stewart_platform.i: src/stewart_platform.cpp.i

.PHONY : src/stewart_platform.i

# target to preprocess a source file
src/stewart_platform.cpp.i:
	$(MAKE) -f CMakeFiles/stewart_platform.dir/build.make CMakeFiles/stewart_platform.dir/src/stewart_platform.cpp.i
.PHONY : src/stewart_platform.cpp.i

src/stewart_platform.s: src/stewart_platform.cpp.s

.PHONY : src/stewart_platform.s

# target to generate assembly for a file
src/stewart_platform.cpp.s:
	$(MAKE) -f CMakeFiles/stewart_platform.dir/build.make CMakeFiles/stewart_platform.dir/src/stewart_platform.cpp.s
.PHONY : src/stewart_platform.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... stewart_platform"
	@echo "... edit_cache"
	@echo "... src/joystick.o"
	@echo "... src/joystick.i"
	@echo "... src/joystick.s"
	@echo "... src/pos.o"
	@echo "... src/pos.i"
	@echo "... src/pos.s"
	@echo "... src/stewart_platform.o"
	@echo "... src/stewart_platform.i"
	@echo "... src/stewart_platform.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

