stp::Gnuplot_sim Class Reference
#include <gnuplot_sim.hpp>
Classes
struct Plot
Public Member Functions
Gnuplot_sim (double deltas[4], double a, double l)
double * new_pos (double T[3], double theta[3])
void update_draw ()
void draw ()
Private Attributes
Plot m_plot
Additional Inherited Members
Detailed Description
Definition at line 12 of file gnuplot_sim.hpp.
Constructor & Destructor Documentation
Gnuplot_sim()
stp::Gnuplot_sim::Gnuplot_sim (double deltas[4], double a, double l) [inline]
Definition at line 15 of file gnuplot_sim.hpp.
References stp::Gnuplot_sim::Plot::A, stp::Gnuplot_sim::Plot::B, stp::Model::m_B, m_plot, NB_LEGS, and stp::Gnuplot_sim::Plot::P.
Member Function Documentation
draw()
void stp::Gnuplot_sim::draw ()
Definition at line 4 of file gnuplot_sim.cpp.
References stp::Gnuplot_sim::Plot::A, stp::Gnuplot_sim::Plot::B, stp::Gnuplot_sim::Plot::gp, stp::Model::m_B, M_PI, m_plot, stp::Model::m_radius, NB_LEGS, and stp::Gnuplot_sim::Plot::P.
Referenced by update_draw().
new_pos()
double* stp::Gnuplot_sim::new_pos (double T[3], double theta[3]) [inline]
Definition at line 31 of file gnuplot_sim.hpp.
References stp::Model::m_alpha, stp::Model::new_pos(), and update_draw().
Referenced by main().
update_draw()
void stp::Gnuplot_sim::update_draw () [inline]
Definition at line 40 of file gnuplot_sim.hpp.
References stp::Gnuplot_sim::Plot::A, draw(), stp::Model::m_a, stp::Model::m_A, stp::Model::m_alpha, stp::Model::m_B, stp::Model::m_beta, stp::Model::m_P, m_plot, NB_LEGS, and stp::Gnuplot_sim::Plot::P.
Referenced by new_pos().
Member Data Documentation
m_plot
Plot stp::Gnuplot_sim::m_plot [private]
Definition at line 66 of file gnuplot_sim.hpp.
Referenced by draw(), Gnuplot_sim(), and update_draw().
The documentation for this class was generated from the following files:
include/gnuplot_sim.hpp
src/gnuplot_sim.cpp