gnuplotio::ArrayTraits< T, Enable > Class Template Reference
#include <gnuplot-iostream.h>
Public Types
typedef Error_WasNotContainer value_type
typedef Error_WasNotContainer range_type
Static Public Member Functions
static range_type get_range (const T &)
Static Public Attributes
static const bool is_container = false
static const bool allow_auto_unwrap = false
static const size_t depth = 0
Detailed Description
template<typename T, typename Enable = void>
class gnuplotio::ArrayTraits< T, Enable >
Definition at line 807 of file gnuplot-iostream.h.
Member Typedef Documentation
range_type
template<typename T, typename Enable = void>
typedef Error_WasNotContainer gnuplotio::ArrayTraits< T, Enable >::range_type
Definition at line 812 of file gnuplot-iostream.h.
value_type
template<typename T, typename Enable = void>
typedef Error_WasNotContainer gnuplotio::ArrayTraits< T, Enable >::value_type
Definition at line 810 of file gnuplot-iostream.h.
Member Function Documentation
get_range()
template<typename T, typename Enable = void>
static range_type gnuplotio::ArrayTraits< T, Enable >::get_range (const T &) [inline], [static]
Definition at line 824 of file gnuplot-iostream.h.
Referenced by gnuplotio::IteratorRange< TI, TV >::deref_subiter(), gnuplotio::get_columns_range(), gnuplotio::ArrayTraits< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, is_boost_tuple_nulltype< typename T::tail_type > > >::type >::get_range(), and gnuplotio::handle_colunwrap_tag().
Member Data Documentation
allow_auto_unwrap
template<typename T, typename Enable = void>
const bool gnuplotio::ArrayTraits< T, Enable >::allow_auto_unwrap = false [static]
Definition at line 819 of file gnuplot-iostream.h.
depth
template<typename T, typename Enable = void>
const size_t gnuplotio::ArrayTraits< T, Enable >::depth = 0 [static]
Definition at line 821 of file gnuplot-iostream.h.
is_container
template<typename T, typename Enable = void>
const bool gnuplotio::ArrayTraits< T, Enable >::is_container = false [static]
Definition at line 814 of file gnuplot-iostream.h.
The documentation for this class was generated from the following file:
include/gnuplot-iostream.h