LXM32 Class Reference
#include <Lexium32A_canopen.h>
Public Member Functions
LXM32 (const char *ifname, uint16_t can_id, bool verbose=false)
Constructor.
bool is_available ()
return true if the can interface is available
int32_t init ()
void start (int8_t mode, uint16_t control)
void stop ()
void set_mode (int8_t mode)
void setSpeed (uint32_t speed)
void setAccel (uint32_t acc)
void setDecel (uint32_t dec)
void new_pos (int32_t pos)
void get_param ()
void print_status ()
void print_control ()
Private Attributes
bool m_verbose
bool m_available
Canopen_socket m_can
Canopen_socket m_can_PDO1
Canopen_socket m_can_PDO2
Canopen_socket m_can_PDO3
Canopen_socket m_can_PDO4
Canopen_socket m_can_SDO
uint8_t m_can_id
uint16_t m_can_baud
uint16_t m_dcom_status
uint16_t m_dcom_control
int8_t m_dcom_mode
int32_t m_PPp_target
int32_t m_PPv_target = 60
uint16_t m_PPoption
uint8_t m_op_state
const char * m_op_state_str [8]
uint8_t m_ctrl_state
const char * m_op_control_str [8]
Detailed Description
Definition at line 40 of file Lexium32A_canopen.h.
Constructor & Destructor Documentation
LXM32()
LXM32::LXM32 (const char * ifname, uint16_t can_id, bool verbose = false)
Constructor.
Parameters
ifname : Name of the CAN interface.
can_id : Node CAN ID of the driver.
Definition at line 3 of file Lexium32A_canopen.cpp.
References Canopen_socket::is_available(), m_available, m_can, m_can_id, m_can_SDO, REG_CANaddress, SDO_R, and Canopen_socket::send_SDO().
Member Function Documentation
get_param()
void LXM32::get_param ()
Definition at line 152 of file Lexium32A_canopen.cpp.
References m_available, m_can, m_can_baud, m_can_id, REG_CANaddress, REG_CANbaud, SDO_R, and Canopen_socket::send_SDO().
Referenced by is_available().
init()
int32_t LXM32::init ()
Definition at line 23 of file Lexium32A_canopen.cpp.
References m_available, m_can_baud, m_can_id, m_can_SDO, m_dcom_status, m_verbose, print_status(), R_PDO, REG__DCOMstatus, REG_CANaddress, REG_CANbaud, SDO_R, Canopen_socket::send_SDO(), Canopen_socket::set_PDO(), setAccel(), setDecel(), setSpeed(), and T_PDO.
Referenced by is_available().
is_available()
bool LXM32::is_available () [inline]
return true if the can interface is available
Definition at line 54 of file Lexium32A_canopen.h.
References get_param(), init(), m_available, new_pos(), print_control(), print_status(), set_mode(), setAccel(), setDecel(), setSpeed(), start(), and stop().
new_pos()
void LXM32::new_pos (int32_t pos)
Definition at line 118 of file Lexium32A_canopen.cpp.
References m_available, m_can, m_can_id, m_dcom_control, m_dcom_mode, m_PPp_target, MODE_ProfilePosition, PPctrl_SET_POINT, and Canopen_socket::send_PDO().
Referenced by is_available().
print_control()
void LXM32::print_control ()
Definition at line 227 of file Lexium32A_canopen.cpp.
References m_available, m_ctrl_state, m_dcom_control, m_dcom_mode, m_dcom_status, m_op_control_str, OP_DISABLEOP, OP_DISABLEVOL, OP_ENABLEOP, OP_FAULTRESEST, OP_QUICKSTOP, OP_SHUTDOWN, and OP_SWITCHON.
Referenced by is_available(), and start().
print_status()
void LXM32::print_status ()
Definition at line 165 of file Lexium32A_canopen.cpp.
References m_available, m_can_baud, m_can_id, m_dcom_mode, m_dcom_status, m_op_state, and m_op_state_str.
Referenced by init(), and is_available().
set_mode()
void LXM32::set_mode (int8_t mode)
Definition at line 138 of file Lexium32A_canopen.cpp.
References m_available, m_can, m_can_id, m_dcom_mode, MODE_ProfilePosition, REG_DCOMopmode, SDO_W, and Canopen_socket::send_SDO().
Referenced by is_available(), and start().
setAccel()
void LXM32::setAccel (uint32_t acc)
Definition at line 65 of file Lexium32A_canopen.cpp.
References m_available, m_can_id, m_can_SDO, REG_RAMP_v_acc, SDO_W, and Canopen_socket::send_SDO().
Referenced by init(), and is_available().
setDecel()
void LXM32::setDecel (uint32_t dec)
Definition at line 73 of file Lexium32A_canopen.cpp.
References m_available, m_can_id, m_can_SDO, REG_RAMP_v_dec, SDO_W, and Canopen_socket::send_SDO().
Referenced by init(), and is_available().
setSpeed()
void LXM32::setSpeed (uint32_t speed)
Definition at line 57 of file Lexium32A_canopen.cpp.
References m_available, m_can_id, m_can_SDO, REG_PPv_target, SDO_W, and Canopen_socket::send_SDO().
Referenced by init(), and is_available().
start()
void LXM32::start (int8_t mode, uint16_t control)
Definition at line 82 of file Lexium32A_canopen.cpp.
References m_available, m_can, m_can_id, m_dcom_control, m_PPp_target, m_verbose, NMT_START, OP_DISABLEVOL, OP_ENABLEOP, print_control(), Canopen_socket::send_NMT(), Canopen_socket::send_PDO(), and set_mode().
Referenced by is_available().
stop()
void LXM32::stop ()
Definition at line 106 of file Lexium32A_canopen.cpp.
References m_available, m_can, m_can_id, NMT_STOP, OP_DISABLEVOL, Canopen_socket::send_NMT(), and Canopen_socket::send_PDO().
Referenced by is_available().
Member Data Documentation
m_available
bool LXM32::m_available [private]
Definition at line 92 of file Lexium32A_canopen.h.
Referenced by get_param(), init(), is_available(), LXM32(), new_pos(), print_control(), print_status(), set_mode(), setAccel(), setDecel(), setSpeed(), start(), and stop().
m_can
Canopen_socket LXM32::m_can [private]
Definition at line 94 of file Lexium32A_canopen.h.
Referenced by get_param(), LXM32(), new_pos(), set_mode(), start(), and stop().
m_can_baud
uint16_t LXM32::m_can_baud [private]
Definition at line 104 of file Lexium32A_canopen.h.
Referenced by get_param(), init(), and print_status().
m_can_id
uint8_t LXM32::m_can_id [private]
Definition at line 103 of file Lexium32A_canopen.h.
Referenced by get_param(), init(), LXM32(), new_pos(), print_status(), set_mode(), setAccel(), setDecel(), setSpeed(), start(), and stop().
m_can_PDO1
Canopen_socket LXM32::m_can_PDO1 [private]
Definition at line 96 of file Lexium32A_canopen.h.
m_can_PDO2
Canopen_socket LXM32::m_can_PDO2 [private]
Definition at line 97 of file Lexium32A_canopen.h.
m_can_PDO3
Canopen_socket LXM32::m_can_PDO3 [private]
Definition at line 98 of file Lexium32A_canopen.h.
m_can_PDO4
Canopen_socket LXM32::m_can_PDO4 [private]
Definition at line 99 of file Lexium32A_canopen.h.
m_can_SDO
Canopen_socket LXM32::m_can_SDO [private]
Definition at line 101 of file Lexium32A_canopen.h.
Referenced by init(), LXM32(), setAccel(), setDecel(), and setSpeed().
m_ctrl_state
uint8_t LXM32::m_ctrl_state [private]
Definition at line 120 of file Lexium32A_canopen.h.
Referenced by print_control().
m_dcom_control
uint16_t LXM32::m_dcom_control [private]
Definition at line 106 of file Lexium32A_canopen.h.
Referenced by new_pos(), print_control(), and start().
m_dcom_mode
int8_t LXM32::m_dcom_mode [private]
Definition at line 108 of file Lexium32A_canopen.h.
Referenced by new_pos(), print_control(), print_status(), and set_mode().
m_dcom_status
uint16_t LXM32::m_dcom_status [private]
Definition at line 105 of file Lexium32A_canopen.h.
Referenced by init(), print_control(), and print_status().
m_op_control_str
const char* LXM32::m_op_control_str[8] [private]
Initial value:
= {"SHUTDOWN", "SWITCH ON",
                                       "DISABLE VOLTAGE", "QUICK STOP",
                                       "DISABLE OPERATION", "ENABLE OPERATION",
                                       "FAULT RESET"}
Definition at line 121 of file Lexium32A_canopen.h.
Referenced by print_control().
m_op_state
uint8_t LXM32::m_op_state [private]
Definition at line 115 of file Lexium32A_canopen.h.
Referenced by print_status().
m_op_state_str
const char* LXM32::m_op_state_str[8] [private]
Initial value:
= {
        "DISABLED", "NOT READY", "READY", "ON",
        "ENABLED", "QUICK STOP", "FAULT", "FAULT, REACTION ACTIVE"}
Definition at line 116 of file Lexium32A_canopen.h.
Referenced by print_status().
m_PPoption
uint16_t LXM32::m_PPoption [private]
Definition at line 113 of file Lexium32A_canopen.h.
m_PPp_target
int32_t LXM32::m_PPp_target [private]
Definition at line 111 of file Lexium32A_canopen.h.
Referenced by new_pos(), and start().
m_PPv_target
int32_t LXM32::m_PPv_target = 60 [private]
Definition at line 112 of file Lexium32A_canopen.h.
m_verbose
bool LXM32::m_verbose [private]
Definition at line 91 of file Lexium32A_canopen.h.
Referenced by init(), and start().
The documentation for this class was generated from the following files:
lib/lxm32/include/Lexium32A_canopen.h
lib/lxm32/src/Lexium32A_canopen.cpp