lib/lxm32/lib/canopen/src/main.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <cstdint>
#include <net/if.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <linux/can.h>
#include <linux/can/raw.h>
#include `canopen_socket.h`
Functions
void usage (char **argv)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 31 of file main.cpp.
References SDO_R, SDO_W, Canopen_socket::send_SDO(), and usage().
usage()
void usage (char ** argv)
Definition at line 17 of file main.cpp.
Referenced by main().