gnuplotio Namespace Reference
Classes
class ArrayTraits
class ArrayTraits< std::pair< T, U > >
class ArrayTraits< T & >
class ArrayTraits< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, boost::mpl::not_< is_boost_tuple_nulltype< typename T::tail_type > > > >::type >
class ArrayTraits< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, is_boost_tuple_nulltype< typename T::tail_type > > >::type >
class ArrayTraits< T, typename boost::enable_if< is_like_stl_container< T > >::type >
class ArrayTraits< T[N]>
class ArrayTraitsDefaults
struct BinarySender
struct BinarySender< boost::int16_t >
struct BinarySender< boost::int32_t >
struct BinarySender< boost::int64_t >
struct BinarySender< boost::int8_t >
struct BinarySender< boost::uint16_t >
struct BinarySender< boost::uint32_t >
struct BinarySender< boost::uint64_t >
struct BinarySender< boost::uint8_t >
struct BinarySender< double >
struct BinarySender< float >
struct BinarySender< std::complex< T > >
struct BinarySender< std::pair< T, U > >
struct BinarySender< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, boost::mpl::not_< is_boost_tuple_nulltype< typename T::tail_type > > > >::type >
struct BinarySender< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, is_boost_tuple_nulltype< typename T::tail_type > > >::type >
struct BinfmtSender
struct BinfmtSender< boost::int16_t >
struct BinfmtSender< boost::int32_t >
struct BinfmtSender< boost::int64_t >
struct BinfmtSender< boost::int8_t >
struct BinfmtSender< boost::uint16_t >
struct BinfmtSender< boost::uint32_t >
struct BinfmtSender< boost::uint64_t >
struct BinfmtSender< boost::uint8_t >
struct BinfmtSender< double >
struct BinfmtSender< float >
struct BinfmtSender< std::complex< T > >
struct BinfmtSender< std::pair< T, U > >
struct BinfmtSender< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, boost::mpl::not_< is_boost_tuple_nulltype< typename T::tail_type > > > >::type >
struct BinfmtSender< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, is_boost_tuple_nulltype< typename T::tail_type > > >::type >
struct CastIntTextSender
struct ColUnwrapNo
struct ColUnwrapYes
struct dont_treat_as_stl_container
struct Error_InappropriateDeref
struct Error_WasNotContainer
struct FileHandleWrapper
struct FlatBinarySender
struct FloatTextSender
class Gnuplot
class GnuplotFeedback
struct is_boost_tuple
struct is_boost_tuple_nulltype
struct is_boost_tuple_nulltype< boost::tuples::null_type >
struct is_like_stl_container
class IteratorRange
struct Mode1D
struct Mode1DUnwrap
struct Mode2D
struct Mode2DUnwrap
struct ModeAuto
struct ModeAutoDecoder
struct ModeAutoDecoder< T, typename boost::enable_if_c<(ArrayTraits< T >::depth==1) >::type >
struct ModeAutoDecoder< T, typename boost::enable_if_c<(ArrayTraits< T >::depth==2) &&!ArrayTraits< T >::allow_auto_unwrap >::type >
struct ModeAutoDecoder< T, typename boost::enable_if_c<(ArrayTraits< T >::depth==2) &&ArrayTraits< T >::allow_auto_unwrap >::type >
struct ModeBinary
struct ModeBinfmt
struct ModeSize
struct ModeText
class PairOfRange
class plotting_empty_container
struct TextSender
struct TextSender< char >
struct TextSender< double >
struct TextSender< float >
struct TextSender< long double >
struct TextSender< signed char >
struct TextSender< std::complex< T > >
struct TextSender< std::pair< T, U > >
struct TextSender< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, boost::mpl::not_< is_boost_tuple_nulltype< typename T::tail_type > > > >::type >
struct TextSender< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, is_boost_tuple_nulltype< typename T::tail_type > > >::type >
struct TextSender< unsigned char >
class VecOfRange
Functions
template<typename T >
VecOfRange< typename ArrayTraits< T >::range_type::subiter_type > get_columns_range (const T &arg)
template<typename T >
void send_scalar (std::ostream &stream, const T &arg, ModeText)
template<typename T >
void send_scalar (std::ostream &stream, const T &arg, ModeBinary)
template<typename T >
void send_scalar (std::ostream &stream, const T &, ModeBinfmt)
template<typename T , typename PrintMode >
boost::disable_if_c< T::is_container >::type deref_and_print (std::ostream &stream, const T &arg, PrintMode)
template<typename T , typename PrintMode >
boost::enable_if_c< T::is_container >::type deref_and_print (std::ostream &stream, const T &arg, PrintMode)
template<typename T , typename U , typename PrintMode >
void deref_and_print (std::ostream &stream, const PairOfRange< T, U > &arg, PrintMode)
template<typename T , typename PrintMode >
void deref_and_print (std::ostream &stream, const VecOfRange< T > &arg, PrintMode)
template<size_t Depth, typename T , typename PrintMode >
boost::enable_if_c<(Depth==1) &&!PrintMode::is_size >::type print_block (std::ostream &stream, T &arg, PrintMode)
template<size_t Depth, typename T , typename PrintMode >
boost::enable_if_c<(Depth >1) &&!PrintMode::is_size >::type print_block (std::ostream &stream, T &arg, PrintMode)
template<typename T >
size_t get_range_size (const T &arg)
template<size_t Depth, typename T , typename PrintMode >
boost::enable_if_c<(Depth==1) &&PrintMode::is_size >::type print_block (std::ostream &stream, T &arg, PrintMode)
template<size_t Depth, typename T , typename PrintMode >
boost::enable_if_c<(Depth >1) &&PrintMode::is_size >::type print_block (std::ostream &stream, T &arg, PrintMode)
template<size_t Depth, typename T , typename PrintMode >
void handle_colunwrap_tag (std::ostream &stream, const T &arg, ColUnwrapNo, PrintMode)
template<size_t Depth, typename T , typename PrintMode >
void handle_colunwrap_tag (std::ostream &stream, const T &arg, ColUnwrapYes, PrintMode)
template<typename T , typename PrintMode >
void handle_organization_tag (std::ostream &stream, const T &arg, Mode1D, PrintMode)
template<typename T , typename PrintMode >
void handle_organization_tag (std::ostream &stream, const T &arg, Mode2D, PrintMode)
template<typename T , typename PrintMode >
void handle_organization_tag (std::ostream &stream, const T &arg, Mode1DUnwrap, PrintMode)
template<typename T , typename PrintMode >
void handle_organization_tag (std::ostream &stream, const T &arg, Mode2DUnwrap, PrintMode)
template<typename T , typename PrintMode >
void handle_organization_tag (std::ostream &stream, const T &arg, ModeAuto, PrintMode)
template<typename T , typename OrganizationMode , typename PrintMode >
void top_level_array_sender (std::ostream &stream, const T &arg, OrganizationMode, PrintMode)
Function Documentation
deref_and_print() [1/4]
template<typename T , typename PrintMode >
boost::disable_if_c<T::is_container>::type gnuplotio::deref_and_print (std::ostream & stream, const T & arg, PrintMode)
Definition at line 1317 of file gnuplot-iostream.h.
References send_scalar().
Referenced by deref_and_print(), and print_block().
deref_and_print() [2/4]
template<typename T , typename PrintMode >
boost::enable_if_c<T::is_container>::type gnuplotio::deref_and_print (std::ostream & stream, const T & arg, PrintMode)
Definition at line 1327 of file gnuplot-iostream.h.
References deref_and_print().
deref_and_print() [3/4]
template<typename T , typename U , typename PrintMode >
void gnuplotio::deref_and_print (std::ostream & stream, const PairOfRange< T, U > & arg, PrintMode)
Definition at line 1344 of file gnuplot-iostream.h.
References deref_and_print(), gnuplotio::PairOfRange< RT, RU >::l, and gnuplotio::PairOfRange< RT, RU >::r.
deref_and_print() [4/4]
template<typename T , typename PrintMode >
void gnuplotio::deref_and_print (std::ostream & stream, const VecOfRange< T > & arg, PrintMode)
Definition at line 1352 of file gnuplot-iostream.h.
References deref_and_print(), and gnuplotio::VecOfRange< RT >::rvec.
get_columns_range()
template<typename T >
VecOfRange<typename ArrayTraits<T>::range_type::subiter_type> gnuplotio::get_columns_range (const T & arg)
Definition at line 1150 of file gnuplot-iostream.h.
References gnuplotio::ArrayTraits< T, Enable >::get_range().
Referenced by handle_colunwrap_tag().
get_range_size()
template<typename T >
size_t gnuplotio::get_range_size (const T & arg)
Definition at line 1418 of file gnuplot-iostream.h.
Referenced by print_block().
handle_colunwrap_tag() [1/2]
template<size_t Depth, typename T , typename PrintMode >
void gnuplotio::handle_colunwrap_tag (std::ostream & stream, const T & arg, ColUnwrapNo , PrintMode)
Definition at line 1453 of file gnuplot-iostream.h.
References gnuplotio::ArrayTraits< T, Enable >::get_range(), and GNUPLOT_STATIC_ASSERT_MSG.
handle_colunwrap_tag() [2/2]
template<size_t Depth, typename T , typename PrintMode >
void gnuplotio::handle_colunwrap_tag (std::ostream & stream, const T & arg, ColUnwrapYes , PrintMode)
Definition at line 1460 of file gnuplot-iostream.h.
References get_columns_range(), and GNUPLOT_STATIC_ASSERT_MSG.
handle_organization_tag() [1/5]
template<typename T , typename PrintMode >
void gnuplotio::handle_organization_tag (std::ostream & stream, const T & arg, Mode1D , PrintMode)
Definition at line 1476 of file gnuplot-iostream.h.
Referenced by handle_organization_tag(), and top_level_array_sender().
handle_organization_tag() [2/5]
template<typename T , typename PrintMode >
void gnuplotio::handle_organization_tag (std::ostream & stream, const T & arg, Mode2D , PrintMode)
Definition at line 1481 of file gnuplot-iostream.h.
handle_organization_tag() [3/5]
template<typename T , typename PrintMode >
void gnuplotio::handle_organization_tag (std::ostream & stream, const T & arg, Mode1DUnwrap , PrintMode)
Definition at line 1486 of file gnuplot-iostream.h.
handle_organization_tag() [4/5]
template<typename T , typename PrintMode >
void gnuplotio::handle_organization_tag (std::ostream & stream, const T & arg, Mode2DUnwrap , PrintMode)
Definition at line 1491 of file gnuplot-iostream.h.
handle_organization_tag() [5/5]
template<typename T , typename PrintMode >
void gnuplotio::handle_organization_tag (std::ostream & stream, const T & arg, ModeAuto , PrintMode)
Definition at line 1496 of file gnuplot-iostream.h.
References handle_organization_tag().
print_block() [1/4]
template<size_t Depth, typename T , typename PrintMode >
boost::enable_if_c<(Depth==1) && !PrintMode::is_size>::type gnuplotio::print_block (std::ostream & stream, T & arg, PrintMode)
Definition at line 1381 of file gnuplot-iostream.h.
References deref_and_print().
Referenced by print_block().
print_block() [2/4]
template<size_t Depth, typename T , typename PrintMode >
boost::enable_if_c<(Depth>1) && !PrintMode::is_size>::type gnuplotio::print_block (std::ostream & stream, T & arg, PrintMode)
Definition at line 1397 of file gnuplot-iostream.h.
References print_block().
print_block() [3/4]
template<size_t Depth, typename T , typename PrintMode >
boost::enable_if_c<(Depth==1) && PrintMode::is_size>::type gnuplotio::print_block (std::ostream & stream, T & arg, PrintMode)
Definition at line 1428 of file gnuplot-iostream.h.
References get_range_size().
print_block() [4/4]
template<size_t Depth, typename T , typename PrintMode >
boost::enable_if_c<(Depth>1) && PrintMode::is_size>::type gnuplotio::print_block (std::ostream & stream, T & arg, PrintMode)
Definition at line 1435 of file gnuplot-iostream.h.
References get_range_size(), and print_block().
send_scalar() [1/3]
template<typename T >
void gnuplotio::send_scalar (std::ostream & stream, const T & arg, ModeText)
Definition at line 1292 of file gnuplot-iostream.h.
References gnuplotio::TextSender< T, Enable >::send().
Referenced by deref_and_print().
send_scalar() [2/3]
template<typename T >
void gnuplotio::send_scalar (std::ostream & stream, const T & arg, ModeBinary)
Definition at line 1297 of file gnuplot-iostream.h.
References gnuplotio::BinarySender< T, Enable >::send().
send_scalar() [3/3]
template<typename T >
void gnuplotio::send_scalar (std::ostream & stream, const T & , ModeBinfmt)
Definition at line 1302 of file gnuplot-iostream.h.
References gnuplotio::BinfmtSender< T, Enable >::send().
top_level_array_sender()
template<typename T , typename OrganizationMode , typename PrintMode >
void gnuplotio::top_level_array_sender (std::ostream & stream, const T & arg, OrganizationMode , PrintMode)
Definition at line 1509 of file gnuplot-iostream.h.
References handle_organization_tag().
Referenced by gnuplotio::Gnuplot::binaryFile(), gnuplotio::Gnuplot::binfmt(), gnuplotio::Gnuplot::file(), gnuplotio::Gnuplot::send(), and gnuplotio::Gnuplot::sendBinary().