src/main.cpp File Reference
#include `joystick.h`
#include `gnuplot_sim.hpp`
Macros
#define MAX_JOY 32767.
#define ANG_MAX 0.06
#define TRANS_MAX 0.06
Functions
int main ()
Macro Definition Documentation
ANG_MAX
#define ANG_MAX 0.06
Definition at line 4 of file main.cpp.
Referenced by main().
MAX_JOY
#define MAX_JOY 32767.
Definition at line 3 of file main.cpp.
Referenced by main().
TRANS_MAX
#define TRANS_MAX 0.06
Definition at line 5 of file main.cpp.
Referenced by main().
Function Documentation
main()
int main ()
Definition at line 8 of file main.cpp.
References ANG_MAX, cJoystick::buttonPressed(), stp::Model::get_T(), stp::Model::init_pos(), cJoystick::joystickValue(), MAX_JOY, stp::Gnuplot_sim::new_pos(), and TRANS_MAX.