Canopen_socket Class Reference
Canopen object able to send command through a CAN interface using the UNIX socket.
#include <canopen_socket.h>
Public Member Functions
Canopen_socket (const char *ifname, bool verbose=false)
Constructor.
Canopen_socket (const char *ifname, uint32_t COBID, bool verbose=false)
Constructor.
bool is_available ()
return true if the can interface is available
template<typename T = uint64_t>
int32_t send_SDO (uint8_t nodeID, bool w, uint32_t index, T &data=AVAL)
templated function to send SDO message with different kind of data type (uint8_t, uint16_t ...)
template<typename T = uint64_t>
int32_t send_SDO (uint8_t nodeID, bool w, uint16_t index, uint8_t subindex, T &data=AVAL)
templated function to send SDO message with different kind of data type (uint8_t, uint16_t ...)
template<uint8_t N, uint8_t U = R_PDO>
int32_t set_PDO (uint8_t nodeID)
template<uint8_t N, typename T , typename S = uint64_t>
int32_t send_PDO (uint8_t nodeID, T data1, S data2=0)
templated function to send PDO1 message with different kind of data type (uint8_t, uint16_t ...)
template<typename T , typename S = uint64_t>
int32_t send_PDO (uint8_t pdo_n, uint8_t nodeID, T data1, S data2=0)
templated function to send PDO message with different kind of data type (uint8_t, uint16_t ...)
int32_t send_NMT (uint16_t msg)
templated function to send NMT CAN message.
template<typename T , typename S = uint64_t>
int32_t send_msg (uint32_t COB_ID, T data1, S data2=0)
templated function to send CAN message.
template<typename T , typename S = uint64_t>
int32_t recv (T &data1, S &data2=AVAL)
templated function to read message with different kind of data type (uint8_t, uint16_t ...)
void print_frame (struct can_frame frame)
Function to print SDO message.
Private Attributes
int m_socket
char m_ifname [20]
struct can_filter m_rfilter [1]
struct sockaddr_can m_addr
struct can_frame m_frame
struct ifreq m_ifr
bool m_verbose
bool m_ifavailable
Detailed Description
Canopen object able to send command through a CAN interface using the UNIX socket.
Definition at line 50 of file canopen_socket.h.
Constructor & Destructor Documentation
Canopen_socket() [1/2]
Canopen_socket::Canopen_socket (const char * ifname, bool verbose = false)
Constructor.
Parameters
ifname : Name of the can interface ex:`can0`
verbose : Display the different message sent.
Definition at line 3 of file canopen_socket.cpp.
References m_addr, m_ifavailable, m_ifname, m_ifr, and m_socket.
Canopen_socket() [2/2]
Canopen_socket::Canopen_socket (const char * ifname, uint32_t COBID, bool verbose = false) [inline]
Constructor.
Parameters
ifname : Name of the can interface ex:`can0`
COBID : Filtering only frame with this ID.
verbose : Display the different message sent.
Definition at line 66 of file canopen_socket.h.
References m_rfilter, and m_socket.
Member Function Documentation
is_available()
bool Canopen_socket::is_available () [inline]
return true if the can interface is available
Definition at line 87 of file canopen_socket.h.
References m_ifavailable.
Referenced by LXM32::LXM32().
print_frame()
void Canopen_socket::print_frame (struct can_frame frame)
Function to print SDO message.
Parameters
frame :CAN frame to print
Definition at line 36 of file canopen_socket.cpp.
recv()
template<typename T , typename S = uint64_t>
int32_t Canopen_socket::recv (T & data1, S & data2 = AVAL) [inline]
templated function to read message with different kind of data type (uint8_t, uint16_t ...)
Parameters
T : Data type.
S : Data type.
data1 : The data to read, can be any data type. (uint8_t, uint16_t ...)
data2 : The data to read, can be any data type. (uint8_t, uint16_t ...)
Returns
Return -1:couldn't read -2:couldn't read full frame >=0:frame CAN ID
Definition at line 265 of file canopen_socket.h.
send_msg()
template<typename T , typename S = uint64_t>
int32_t Canopen_socket::send_msg (uint32_t COB_ID, T data1, S data2 = 0) [inline]
templated function to send CAN message.
Parameters
T : Data type.
S : Data type.
nodeID : COBID of the messae to send
data1 : The data to write, can be any data type. (uint8_t, uint16_t ...)
data2 : The data to write, can be any data type. (uint8_t, uint16_t ...)
Returns
Return number of bytes written
Definition at line 239 of file canopen_socket.h.
References m_frame, and m_socket.
Referenced by send_NMT(), and send_PDO().
send_NMT()
int32_t Canopen_socket::send_NMT (uint16_t msg) [inline]
templated function to send NMT CAN message.
Parameters
msg : NMT message to send.
Returns
Return number of bytes written.
Definition at line 223 of file canopen_socket.h.
References send_msg().
Referenced by LXM32::start(), and LXM32::stop().
send_PDO() [1/2]
template<uint8_t N, typename T , typename S = uint64_t>
int32_t Canopen_socket::send_PDO (uint8_t nodeID, T data1, S data2 = 0) [inline]
templated function to send PDO1 message with different kind of data type (uint8_t, uint16_t ...)
Parameters
N : Number of the PDO.
T : Data type.
nodeID : ID of the destination node. [0-127]
data1 : The data to write, can be any data type. (uint8_t, uint16_t ...)
Returns
Return number of bytes written.
Definition at line 195 of file canopen_socket.h.
Referenced by LXM32::new_pos(), LXM32::start(), and LXM32::stop().
send_PDO() [2/2]
template<typename T , typename S = uint64_t>
int32_t Canopen_socket::send_PDO (uint8_t pdo_n, uint8_t nodeID, T data1, S data2 = 0) [inline]
templated function to send PDO message with different kind of data type (uint8_t, uint16_t ...)
Parameters
T : Data type.
S : Data type.
pdo_n : Number of the PDO to send
nodeID : ID of the destination node. [0-127]
data1 : The data to write, can be any data type. (uint8_t, uint16_t ...)
data2 : The data to write, can be any data type. (uint8_t, uint16_t ...)
Returns
Return number of bytes written.
Definition at line 212 of file canopen_socket.h.
References send_msg().
send_SDO() [1/2]
template<typename T = uint64_t>
int32_t Canopen_socket::send_SDO (uint8_t nodeID, bool w, uint32_t index, T & data = AVAL) [inline]
templated function to send SDO message with different kind of data type (uint8_t, uint16_t ...)
Parameters
nodeID : ID of the destination node. [0-127]
w : Set to SDO_W or SDO_R to respectively write or read a parameter.
index : Register index with the format (unit32_t):0x|(uint16_t)index|(uint8_t)00| (uint16_t)subindex|
data : The data to write, can be any data type. (uint8_t, uint16_t ...)
Returns
Return number of bytes written.
Definition at line 103 of file canopen_socket.h.
Referenced by LXM32::get_param(), LXM32::init(), LXM32::LXM32(), main(), LXM32::set_mode(), set_PDO(), LXM32::setAccel(), LXM32::setDecel(), and LXM32::setSpeed().
send_SDO() [2/2]
template<typename T = uint64_t>
int32_t Canopen_socket::send_SDO (uint8_t nodeID, bool w, uint16_t index, uint8_t subindex, T & data = AVAL) [inline]
templated function to send SDO message with different kind of data type (uint8_t, uint16_t ...)
Parameters
nodeID : ID of the destination node. [0-127]
w : Set to SDO_W or SDO_R to respectively write or read a parameter.
index : Register index.
subindex : Register subindex.
data : The data to write, can be any data type. (uint8_t, uint16_t ...)
Returns
Return number of bytes written.
Definition at line 120 of file canopen_socket.h.
set_PDO()
template<uint8_t N, uint8_t U = R_PDO>
int32_t Canopen_socket::set_PDO (uint8_t nodeID) [inline]
Definition at line 174 of file canopen_socket.h.
References R_PDO, SDO_W, and send_SDO().
Referenced by LXM32::init().
Member Data Documentation
m_addr
struct sockaddr_can Canopen_socket::m_addr [private]
CAN address
Definition at line 303 of file canopen_socket.h.
Referenced by Canopen_socket().
m_frame
struct can_frame Canopen_socket::m_frame [private]
CAN frame
Definition at line 304 of file canopen_socket.h.
Referenced by send_msg().
m_ifavailable
bool Canopen_socket::m_ifavailable [private]
Definition at line 308 of file canopen_socket.h.
Referenced by Canopen_socket(), and is_available().
m_ifname
char Canopen_socket::m_ifname[20] [private]
CAN interface name
Definition at line 299 of file canopen_socket.h.
Referenced by Canopen_socket().
m_ifr
struct ifreq Canopen_socket::m_ifr [private]
CAN interface
Definition at line 305 of file canopen_socket.h.
Referenced by Canopen_socket().
m_rfilter
struct can_filter Canopen_socket::m_rfilter[1] [private]
Definition at line 301 of file canopen_socket.h.
Referenced by Canopen_socket().
m_socket
int Canopen_socket::m_socket [private]
Can socket
Definition at line 298 of file canopen_socket.h.
Referenced by Canopen_socket(), and send_msg().
m_verbose
bool Canopen_socket::m_verbose [private]
Verbose mode
Definition at line 307 of file canopen_socket.h.
The documentation for this class was generated from the following files:
lib/lxm32/lib/canopen/include/canopen_socket.h
lib/lxm32/lib/canopen/src/canopen_socket.cpp