CANopen::Driver Class Reference
Device Profile Drives and Motion Control.
#include <CANopen_driver.h>
Public Types
enum Register : uint32_t {
_DCOMstatus = 0x60410000,
DCOMcontrol = 0x60400000,
DCOMopmode = 0x60600000,
_DCOMopmd_act = 0x60610000,
PPp_target = 0x607A0000,
PPv_target = 0x60810000,
PVv_target = 0x60FF0000,
PTtq_target = 0x60710000,
RAMP_v_acc = 0x60830000,
RAMP_v_dec = 0x60840000,
_p_act = 0x60640000,
_v_act = 0x606C0000,
_tq_act = 0x60770000,
HMmethod = 0x60980000,
HMv = 0x60990001,
HMv_out = 0x60990002
 }
enum OperationMode : int8_t {
ProfilePosition = 1,
Velocity = 2,
ProfileVelocity = 3,
ProfileTorque = 4,
Homing = 6,
InterpolatedPosition = 7
 }
enum State : uint16_t {
mask = 0x006f,
NotReadyToSwitchtON = 0x0000,
SwitchONDisabled = 0x0040,
ReadyToSwitchON = 0x0021,
SwitchedON = 0x0023,
OperationEnabled = 0x0037,
Fault = 0x000f,
FaultReactionActive = 0x000f,
QuickStopActive = 0x0007
 }
enum StatusBits : uint16_t {
ReadyToSwitchOn_bit = 0x0001,
SwitchedOn_bit = 0x0002,
OperationEnabled_bit = 0x0004,
Fault_bit = 0x0008,
VoltageEnabled_bit = 0x0010,
QuickStop_bit = 0x0020,
SwitchONDisabled_bit = 0x0040,
Error0_bit = 0x0080,
HaltRequest_bit = 0x0100,
Remote_bit = 0x0200,
TargetReached_bit = 0x0400,
InternalLimitReached_bit = 0x0800,
OperationMode_bit = 0x1000,
BlockingError_bit = 0x2000,
OperationModeStart_bit = 0x4000,
ValidRef_bit = 0x8000
 }
enum Control : uint16_t {
Shutdown = 0x0006,
SwitchON = 0x0007,
DisableVoltage = 0x0000,
QuickStop = 0x0002,
DisableOperation = 0x0007,
EnableOperation = 0x000f,
FaultResest = 0x0080
 }
enum PDOFunctionCode : uint32_t {
PDO1Transmit = Message::PDO1Transmit,
PDO1Receive = Message::PDO1Receive,
PDO2Transmit = Message::PDO2Transmit,
PDO2Receive = Message::PDO2Receive,
PDO3Transmit = Message::PDO3Transmit,
PDO3Receive = Message::PDO3Receive,
PDO4Transmit = Message::PDO4Transmit,
PDO4Receive = Message::PDO4Receive
 }
Public Member Functions
Driver (const char *ifname, uint16_t can_id, int verbose_lvl=0)
Constructor.
template<typename T >
void set (Register reg, T val, bool force_sdo=false, bool wait=false)
Enables to store a value in a specified registers.
template<typename T >
T get (Register reg, bool force_sdo=false)
get Gets the value of a specified registers.
void set_control (Control ctrl)
set_control : Send transition states order.
State get_state ()
Returns the current state of the driver by reading the status word.
void wait_state (State state, uint16_t _mask=mask)
wait_state loop until the driver state is different from the one passed while(actual_state()&mask) != (state&mask))
void set_mode (OperationMode mode, bool wait=false)
set_mode Set the desired opereration mode.
OperationMode get_mode (bool force_sdo=true)
get_mode Returns the actual operation mode of the driver.
bool set_position (int32_t target, bool absolute=true)
set_position Send the new position to reach. Has to be in ProfilPositon mode to have some effect.
bool set_velocity (int32_t target)
set_velocity Send the new velocity to reach. Has to be in ProfilPositon or ProfilVelocity mode to have some effect.
bool set_torque (int16_t target)
set_torque Send the new torque to reach. Has to be in ProfilTorque mode to have some effect.
int32_t get_position ()
get_position Returns the actual postion of the motor.
int32_t get_velocity ()
get_velocity Returns the actual velocity of the motor.
int32_t get_torque ()
get_torque Returns the actual torque of the motor.
void set_position_offset (int32_t offset_pos)
set_position_offset Set the postion offset of the motor. Rq better to have a large offset to avoid letting the motor switch off in negativ position: it would result in a wrong position when restarting
void start ()
start
void pause ()
pause
void stop ()
stop
void profilePosition_mode ()
profilePosition_mode
void profileVelocity_mode ()
profileVelocity_mode
void profileTorque_mode ()
profileTorque_mode
void homing ()
homing
Parameter * get_param (Register reg)
virtual void print_manufacturer_status ()=0
std::string ctrl_to_str (Control control)
bool is_available ()
return true if the can interface is available
Protected Member Functions
void send (Parameter *param)
send the parameter via a Writting SDO message to the driver
void update (Parameter *param)
Request an update of the parameter via a Reading SDO message. (the parameter has been updated when param->sdo_flag is down.
void map_PDO (PDOFunctionCode fn, Parameter *param, int slot)
Enables to map the different parameters of the driver to the Transmit PDO. When a PDO is received in the T_PDO_socket() thread, the value of the pdo will be stored in the mapped parameter.
void activate_PDO (PDOFunctionCode fn, bool set=true)
Sends a SDO message to activate the specified PDO.
void T_socket ()
void RPDO_socket ()
Protected Attributes
std::thread * m_rpdo_socket_thread
std::atomic_flag rpdo_socket_flag
std::mutex rpdo_mutex
std::thread * m_t_socket_thread
std::atomic_flag t_socket_flag
const char * m_ifname
int m_verbose_level
bool m_available
CANopen::Socket m_socket
std::map< PDOFunctionCode, std::vector< Parameter * > > m_PDO_map
std::map< Register, Parameter * > m_parameters
uint8_t m_node_id
uint16_t m_can_baud
int32_t m_offset_pos = 0
Detailed Description
Device Profile Drives and Motion Control.
Definition at line 27 of file CANopen_driver.h.
Member Enumeration Documentation
Control
enum CANopen::Driver::Control : uint16_t
Possible Control commands
Enumerator
Shutdown goto ReadySwitchON
SwitchON goto SwitchedON
DisableVoltage goto SwitchONDisabled
QuickStop goto QuickStopActiv
DisableOperation goto SwitchedON
EnableOperation goto OperationEnabled
FaultResest goto SwitchONDisabled
Definition at line 160 of file CANopen_driver.h.
OperationMode
enum CANopen::Driver::OperationMode : int8_t
Operational modes
Enumerator
ProfilePosition The positioning of the drive is defined in this mode. Speed, position and acceleration can be limited and profiled moves using a Trajectory Generator are possible as well.
Velocity Many frequency inverters use this simple mode to control the velocity of the drive with limits and ramp functions.
ProfileVelocity The Profile Velocity Mode is used to control the velocity of the drive with no special regard of the position. It supplies limit functions and Trajectory Generation.
ProfileTorque The profile torque mode allows a host (external) control system (i.e. closed-loop speed controller, open-loop transmission force controller) to transmit the target torque value, which is processed via the trajectory generator. The torque slope and torque profile type parameters are required.
Homing Homming mode.
InterpolatedPosition The interpolated position mode is used to control multiple coordinated axles or a single axle with the need for time-interpolation of set-point data. The interpolated position mode normally uses time synchronization mechanisms like the sync object defined in /3/ for a time coordination of the related drive units.
Definition at line 72 of file CANopen_driver.h.
Register
enum CANopen::Driver::Register : uint32_t
CIA 402 CANopen Driver
Enumerator
_DCOMstatus 6041h - The statusword indicates the current state of the drive. No bits are latched. The statusword consist of bits for:
the current state of the drive,
the operating state of the mode and
manufacturer specific options.
DCOMcontrol 6040h - The controlword consist of bits for:
the controlling of the state,
the controlling of operating modes and
manufacturer specific options.
DCOMopmode 6060h - The parameter modes of operation switches the actually choosen operation mode.
_DCOMopmd_act 6061h - The modes of operation display shows the current mode of operation. The meaning of the returned value corresponds to that of the modes of operation option code
PPp_target 607Ah - The target position is the position that the drive should move to in position profile mode using the current settings of motion control parameters such as velocity, acceleration, deceleration, motion profile type etc. The target position is given in user defined position units. It is converted to position increments using the position factor. The target position will be interpreted as absolute or relative depending on the ‘abs / rel' flag in the controlword.
PPv_target 6081h - The profile velocity is the velocity normally attained at the end of the acceleration ramp during a profiled move and is valid for both directions of motion. The profile velocity is given in user defined speed units. It is converted to position increments per second using the velocity encoder factor.
PVv_target 60FFh - The target velocity is the input for the trajectory generator and the value is given in velocity units.
PTtq_target 6071h - This parameter is the input value for the torque controller in profile torque mode and the value is given per thousand of rated torque.
RAMP_v_acc 6083h - The profile acceleration is given in user defined acceleration units. It is converted to position increments per second 2 using the normalizing factors.
RAMP_v_dec 6084h - The profile deceleration is given in the same units as profile acceleration. If this parameter is not supported, then the profile acceleration value is also used for deceleration.
_p_act 6064h - This object represents the actual value of the position measurement device in user defined units.
_v_act 606Ch - The velocity actual value is also represented in velocity units and is coupled to the velocity used as input to the velocity controller.
_tq_act 6077h - The torque actual value corresponds to the instantaneous torque in the drive motor. The value is given per thousand of rated torque.
HMmethod 6098h - The homing method object determines the method that will be used during homing.
HMv 6099h01 - Speed during search for switch.
HMv_out 6099h02 - Speed during search for zero
Definition at line 34 of file CANopen_driver.h.
State
enum CANopen::Driver::State : uint16_t
Possible States
Enumerator
mask Keeping only main state bytes.
NotReadyToSwitchtON Not Ready to Switch ON:
Low level Power (e.g. 15V, 5V) has been applied to the drive.
The drive is being initialized or is running self test.
A brake, if present, has to be applied in this state.
The drive function is disabled.
SwitchONDisabled Switch ON Disabled:
Drive Initialisation is complete.
The drive parameters have been set up.
Drive parameters may be changed.
High Voltage may not be applied to the drive, (e.g. for safety reasons).
The drive function is disabled.
ReadyToSwitchON Ready to Switch ON:
High Voltage may be applied to the drive.
The drive parameters may be changed.
The drive function is disabled
SwitchedON Switched ON:
High Voltage has been applied to the drive.
The Power Amplifier is ready.
The drive parameters may be changed.
The drive function is disabled.
OperationEnabled Operation Enabled:
No faults have been detected.
The drive function is enabled and power is applied to the motor.
The drive parameters may be changed.(This corresponds to normal operation of the drive.)
Fault Fault:
The drive parameters may be changed.
A fault has occured in the drive.
The drive function is disabled.
FaultReactionActive Fault Reaction Active:
The drive parameters may be changed.
A non-fatal fault has occured in the drive.
The Quick Stop function is being executed.
The drive function is enabled and power is applied to the motor.
QuickStopActive Quick Stop Active:
The drive parameters may be changed.The Quick Stop function is being executed.
The drive function is enabled and power is applied to the motor. If the ‘Quick-Stop-Option-Code’ is switched to 5 (Stay in Quick-Stop), you can’t leave the Quick-Stop-State, but you can transmit to ‘Operation Enable’ with the command‘Enable Operation’
Definition at line 91 of file CANopen_driver.h.
Constructor & Destructor Documentation
Driver()
CANopen::Driver::Driver (const char * ifname, uint16_t can_id, int verbose_lvl = 0)
Constructor.
Parameters
ifname : Name of the CAN interface.
can_id : Node CAN ID of the driver.
verbose_lvl : Level of verbosity.
Definition at line 4 of file CANopen_driver.cpp.
References _DCOMstatus.
Member Function Documentation
activate_PDO()
void CANopen::Driver::activate_PDO (PDOFunctionCode fn, bool set = true) [protected]
Sends a SDO message to activate the specified PDO.
Parameters
ifname : N
can_id : Node CAN ID of the driver.
Definition at line 59 of file CANopen_driver.cpp.
ctrl_to_str()
std::string CANopen::Driver::ctrl_to_str (Control control)
< goto ReadySwitchON
< goto SwitchedON
< goto SwitchONDisabled
< goto QuickStopActiv
< goto OperationEnabled
Definition at line 346 of file CANopen_driver.cpp.
get()
template<typename T >
T CANopen::Driver::get (Register reg, bool force_sdo = false) [inline]
get Gets the value of a specified registers.
Parameters
reg : The register to get. (In the format ind__sub)
force_sdo : If true, the parameter will be updated via a reading SDO.
Returns
The value of the register in the templated format T selected.
Definition at line 218 of file CANopen_driver.h.
References update().
get_mode()
OperationMode CANopen::Driver::get_mode (bool force_sdo = true) [inline]
get_mode Returns the actual operation mode of the driver.
Parameters
force_sdo If set a sdo read message will be send to get the mode. Set to false to save some communication time.
Returns
The actual operational mode
Definition at line 267 of file CANopen_driver.h.
References _DCOMopmd_act.
get_position()
int32_t CANopen::Driver::get_position () [inline]
get_position Returns the actual postion of the motor.
Returns
The actual postion of the motor.
Definition at line 297 of file CANopen_driver.h.
References _p_act.
get_state()
State CANopen::Driver::get_state () [inline]
Returns the current state of the driver by reading the status word.
Returns
The current state.
Definition at line 240 of file CANopen_driver.h.
References _DCOMstatus.
Referenced by wait_state().
get_torque()
int32_t CANopen::Driver::get_torque () [inline]
get_torque Returns the actual torque of the motor.
Returns
The actual torque of the motor.
Definition at line 309 of file CANopen_driver.h.
References _tq_act.
get_velocity()
int32_t CANopen::Driver::get_velocity () [inline]
get_velocity Returns the actual velocity of the motor.
Returns
The actual velocity of the motor.
Definition at line 303 of file CANopen_driver.h.
References _v_act.
map_PDO()
void CANopen::Driver::map_PDO (PDOFunctionCode fn, Parameter * param, int slot) [protected]
Enables to map the different parameters of the driver to the Transmit PDO. When a PDO is received in the T_PDO_socket() thread, the value of the pdo will be stored in the mapped parameter.
Parameters
fn : Function code of the PDO.
param : Parameter to map.
slot : Slot of the parameter in the PDO message.
Definition at line 50 of file CANopen_driver.cpp.
References CANopen::Parameter::link_to_pdo().
send()
void CANopen::Driver::send (Parameter * param) [protected]
send the parameter via a Writting SDO message to the driver
Parameters
param Parameter to send.
Definition at line 96 of file CANopen_driver.cpp.
References CANopen::Parameter::payload().
Referenced by set().
set()
template<typename T >
void CANopen::Driver::set (Register reg, T val, bool force_sdo = false, bool wait = false) [inline]
Enables to store a value in a specified registers.
Parameters
reg : The register to set. (In the format ind__sub)
val : The value to store in the register.
force_sdo : If true, the parameter will be send to the driver via a SDO. Else the parametr will be sent via PDO if it was mapped to an activated RPDO.
wait : If set, the function is blocking and wait for the parameter to be sent via SDO.
Definition at line 198 of file CANopen_driver.h.
References send().
set_control()
void CANopen::Driver::set_control (Control ctrl)
set_control : Send transition states order.
Parameters
ctrl : Control to send.
Definition at line 439 of file CANopen_driver.cpp.
set_mode()
void CANopen::Driver::set_mode (OperationMode mode, bool wait = false)
set_mode Set the desired opereration mode.
Parameters
mode Mode to set.
wait Repeatidly test the actual operation mode register until it is eqaual to the selected mode.
Definition at line 429 of file CANopen_driver.cpp.
set_position()
bool CANopen::Driver::set_position (int32_t target, bool absolute = true)
set_position Send the new position to reach. Has to be in ProfilPositon mode to have some effect.
Parameters
target Position to reach (in internal unit)
absolute If set the target will be process as an absolute value. Else it will be procecced as a relative (to the current position) value.
Returns
True if successfully sent.
Definition at line 239 of file CANopen_driver.cpp.
set_position_offset()
void CANopen::Driver::set_position_offset (int32_t offset_pos) [inline]
set_position_offset Set the postion offset of the motor. Rq better to have a large offset to avoid letting the motor switch off in negativ position: it would result in a wrong position when restarting
Parameters
offset_pos Offest of the motor in internal Unit
Definition at line 316 of file CANopen_driver.h.
set_torque()
bool CANopen::Driver::set_torque (int16_t target)
set_torque Send the new torque to reach. Has to be in ProfilTorque mode to have some effect.
Parameters
target Torque to reach (in internal unit)
Returns
True if successfully sent.
Definition at line 275 of file CANopen_driver.cpp.
set_velocity()
bool CANopen::Driver::set_velocity (int32_t target)
set_velocity Send the new velocity to reach. Has to be in ProfilPositon or ProfilVelocity mode to have some effect.
Parameters
target Velocity to reach (in internal unit)
Returns
True if successfully sent.
Definition at line 260 of file CANopen_driver.cpp.
update()
void CANopen::Driver::update (Parameter * param) [protected]
Request an update of the parameter via a Reading SDO message. (the parameter has been updated when param->sdo_flag is down.
Parameters
param Parameter to update.
Definition at line 112 of file CANopen_driver.cpp.
Referenced by get().
wait_state()
void CANopen::Driver::wait_state (State state, uint16_t _mask = mask) [inline]
wait_state loop until the driver state is different from the one passed while(actual_state()&mask) != (state&mask))
Parameters
state State to wait for.
_mask Mask to selected specific bits of the state.
Definition at line 248 of file CANopen_driver.h.
References get_state(), and mask.
The documentation for this class was generated from the following files:
CANopen_driver.h
CANopen_driver.cpp