cJoystick Class Reference
#include <joystick.h>
Public Member Functions
cJoystick ()
~cJoystick ()
void readEv ()
joystick_position joystickPosition (int n)
int joystickValue (int n)
bool buttonPressed (int n)
Static Public Member Functions
static void * loop (void *obj)
Detailed Description
Definition at line 23 of file joystick.h.
Constructor & Destructor Documentation
cJoystick()
cJoystick::cJoystick ()
Definition at line 3 of file joystick.cpp.
References joystick_state::axis, joystick_state::button, JOYSTICK_DEV, and loop().
 cJoystick()
cJoystick::~cJoystick ()
Definition at line 25 of file joystick.cpp.
Member Function Documentation
buttonPressed()
bool cJoystick::buttonPressed (int n)
Definition at line 80 of file joystick.cpp.
References joystick_state::button.
joystickPosition()
joystick_position cJoystick::joystickPosition (int n)
Definition at line 56 of file joystick.cpp.
References joystick_state::axis, joystick_position::r, joystick_position::theta, joystick_position::x, and joystick_position::y.
joystickValue()
int cJoystick::joystickValue (int n)
Definition at line 75 of file joystick.cpp.
References joystick_state::axis.
Referenced by main().
loop()
void * cJoystick::loop (void * obj) [static]
Definition at line 36 of file joystick.cpp.
References readEv().
Referenced by cJoystick().
readEv()
void cJoystick::readEv ()
Definition at line 41 of file joystick.cpp.
References joystick_state::axis, and joystick_state::button.
Referenced by loop().
The documentation for this class was generated from the following files:
/home/adev/Documents/STECH/stewart_platform/lib/lxm32/lib/joystick/include/joystick.h
/home/adev/Documents/STECH/stewart_platform/lib/lxm32/lib/joystick/src/joystick.cpp