gnuplotio::IteratorRange< TI, TV > Class Template Reference
#include <gnuplot-iostream.h>
Public Types
typedef boost::mpl::if_c< is_container, Error_InappropriateDeref, TV >::type value_type
typedef ArrayTraits< TV >::range_type subiter_type
Public Member Functions
IteratorRange ()
IteratorRange (const TI &_it, const TI &_end)
bool is_end () const
void inc ()
value_type deref () const
subiter_type deref_subiter () const
Static Public Attributes
static const bool is_container = ArrayTraits<TV>::is_container
Detailed Description
template<typename TI, typename TV>
class gnuplotio::IteratorRange< TI, TV >
Definition at line 860 of file gnuplot-iostream.h.
Member Typedef Documentation
subiter_type
template<typename TI , typename TV >
typedef ArrayTraits<TV>::range_type gnuplotio::IteratorRange< TI, TV >::subiter_type
Definition at line 868 of file gnuplot-iostream.h.
value_type
template<typename TI , typename TV >
typedef boost::mpl::if_c<is_container, Error_InappropriateDeref, TV>::type gnuplotio::IteratorRange< TI, TV >::value_type
Definition at line 867 of file gnuplot-iostream.h.
Constructor & Destructor Documentation
IteratorRange() [1/2]
template<typename TI , typename TV >
gnuplotio::IteratorRange< TI, TV >::IteratorRange () [inline]
Definition at line 862 of file gnuplot-iostream.h.
IteratorRange() [2/2]
template<typename TI , typename TV >
gnuplotio::IteratorRange< TI, TV >::IteratorRange (const TI & _it, const TI & _end) [inline]
Definition at line 863 of file gnuplot-iostream.h.
Member Function Documentation
deref()
template<typename TI , typename TV >
value_type gnuplotio::IteratorRange< TI, TV >::deref () const [inline]
Definition at line 874 of file gnuplot-iostream.h.
References GNUPLOT_STATIC_ASSERT_MSG, gnuplotio::IteratorRange< TI, TV >::is_container, and gnuplotio::IteratorRange< TI, TV >::is_end().
deref_subiter()
template<typename TI , typename TV >
subiter_type gnuplotio::IteratorRange< TI, TV >::deref_subiter () const [inline]
Definition at line 883 of file gnuplot-iostream.h.
References gnuplotio::ArrayTraits< T, Enable >::get_range(), GNUPLOT_STATIC_ASSERT_MSG, gnuplotio::IteratorRange< TI, TV >::is_container, and gnuplotio::IteratorRange< TI, TV >::is_end().
inc()
template<typename TI , typename TV >
void gnuplotio::IteratorRange< TI, TV >::inc () [inline]
Definition at line 872 of file gnuplot-iostream.h.
is_end()
template<typename TI , typename TV >
bool gnuplotio::IteratorRange< TI, TV >::is_end () const [inline]
Definition at line 870 of file gnuplot-iostream.h.
Referenced by gnuplotio::IteratorRange< TI, TV >::deref(), and gnuplotio::IteratorRange< TI, TV >::deref_subiter().
Member Data Documentation
is_container
template<typename TI , typename TV >
const bool gnuplotio::IteratorRange< TI, TV >::is_container = ArrayTraits<TV>::is_container [static]
Definition at line 865 of file gnuplot-iostream.h.
Referenced by gnuplotio::IteratorRange< TI, TV >::deref(), and gnuplotio::IteratorRange< TI, TV >::deref_subiter().
The documentation for this class was generated from the following file:
/home/adev/Documents/STECH/stewart_platform/include/gnuplot-iostream.h