CANopen::Payload Class Reference
Payload of CANopen message: array of 1 to 8 bytes of data.
#include <payload.h>
Public Member Functions
Payload (const Payload &)=default
Payload (const std::vector< uint8_t > &other)
template<typename T >
Payload (T value)
Payload Constructor from a standard data type variable. It transfrom the n bytes of the data into a array of n bytes.
Payload & operator= (const Payload &)=default
template<typename T >
T & value (unsigned begin=0)
value Returns the data casted as a variable of type T
template<typename T >
Payload & operator<< (T &&value)
operator << Adds a variable inside the payload
Payload & operator<< (Payload &&p)
operator << Adds a variable inside the payload
Payload & store_at (Payload &&p, int slot)
store_at Stores a variable at a specified index in the data array.
operator std::string () const
Detailed Description
Payload of CANopen message: array of 1 to 8 bytes of data.
Definition at line 22 of file payload.h.
Constructor & Destructor Documentation
Payload()
template<typename T >
CANopen::Payload::Payload (T value) [inline]
Payload Constructor from a standard data type variable. It transfrom the n bytes of the data into a array of n bytes.
Parameters
value The variable to store in the payload
Definition at line 33 of file payload.h.
References value().
Member Function Documentation
operator<<() [1/2]
Payload& CANopen::Payload::operator<< (Payload && p) [inline]
operator << Adds a variable inside the payload
Parameters
p The variable to store
Returns
The Payload reference.
Definition at line 74 of file payload.h.
operator<<() [2/2]
template<typename T >
Payload& CANopen::Payload::operator<< (T && value) [inline]
operator << Adds a variable inside the payload
Parameters
value The variable to store
Returns
The Payload reference.
Definition at line 62 of file payload.h.
References value().
store_at()
Payload& CANopen::Payload::store_at (Payload && p, int slot) [inline]
store_at Stores a variable at a specified index in the data array.
Parameters
p The variable to store.
slot The index in data array where the variable has to be store to.
Returns
Definition at line 87 of file payload.h.
value()
template<typename T >
T& CANopen::Payload::value (unsigned begin = 0) [inline]
value Returns the data casted as a variable of type T
Parameters
begin The index of the data array from where the data must be returned.
Returns
The data as a variable of type T.
Definition at line 48 of file payload.h.
Referenced by CANopen::Parameter::from_payload(), operator<<(), and Payload().
The documentation for this class was generated from the following files:
payload.h
payload.cpp