stp::Model Class Reference
#include <model.hpp>
Public Member Functions
Model ()
Model (double deltas[4], double a, double l)
double * new_pos (double T[3], double theta[3])
double get_T (int i)
double get_theta (int i)
void init_pos ()
void compute_R (double theta[3])
Protected Member Functions
void set_T (double t0, double t1, double t2)
void set_T_spd (double t0, double t1, double t2)
void set_theta (double t0, double t1, double t2)
void set_theta_spd (double t0, double t1, double t2)
Protected Attributes
double m_radius [2]
double m_a
double m_a2
double m_l
double m_l2
double _d2 [NB_LEGS]
double m_P [NB_LEGS][3]
double m_P1 [NB_LEGS][3]
double m_B [NB_LEGS][3]
double m_A [NB_LEGS][3]
double m_parity [NB_LEGS]
double m_beta [NB_LEGS]
double m_alpha [NB_LEGS]
double m_gamma [2][NB_LEGS]
double m_T [3]
double m_theta [3]
double m_R [3][3]
double m_trig [6]
double m_T_spd [3]
double m_theta_spd [3]
double m_alpha_spd [6]
double _alphaI [6]
Detailed Description
Definition at line 13 of file model.hpp.
Constructor & Destructor Documentation
Model() [1/2]
stp::Model::Model () [inline]
Definition at line 16 of file model.hpp.
References compute_R(), get_T(), get_theta(), init_pos(), new_pos(), set_T(), set_T_spd(), set_theta(), and set_theta_spd().
Model() [2/2]
stp::Model::Model (double deltas[4], double a, double l)
Definition at line 8 of file model.cpp.
References m_a, m_a2, m_alpha_spd, m_B, m_beta, m_gamma, m_l, m_l2, m_P1, m_parity, M_PI, m_radius, and NB_LEGS.
Member Function Documentation
compute_R()
void stp::Model::compute_R (double theta[3])
Definition at line 117 of file model.cpp.
References m_R, m_theta, and m_trig.
Referenced by Model(), and new_pos().
get_T()
double stp::Model::get_T (int i)
Definition at line 154 of file model.cpp.
References m_T.
Referenced by main(), and Model().
get_theta()
double stp::Model::get_theta (int i)
Definition at line 160 of file model.cpp.
References m_theta.
Referenced by Model().
init_pos()
void stp::Model::init_pos ()
Definition at line 49 of file model.cpp.
References _alphaI, m_a2, m_alpha, m_B, m_l2, m_P1, m_T, m_theta, new_pos(), set_T(), set_T_spd(), set_theta(), and set_theta_spd().
Referenced by main(), and Model().
new_pos()
double * stp::Model::new_pos (double T[3], double theta[3])
Definition at line 68 of file model.cpp.
References _d2, compute_R(), m_a, m_a2, m_alpha, m_B, m_beta, m_l2, m_P, m_P1, m_R, m_T, m_theta, and NB_LEGS.
Referenced by init_pos(), Model(), stp::Gnuplot_sim::new_pos(), and stp::Platform::new_pos().
set_T()
void stp::Model::set_T (double t0, double t1, double t2) [protected]
Definition at line 138 of file model.cpp.
References m_T.
Referenced by init_pos(), and Model().
set_T_spd()
void stp::Model::set_T_spd (double t0, double t1, double t2) [protected]
Definition at line 146 of file model.cpp.
References m_T_spd.
Referenced by init_pos(), and Model().
set_theta()
void stp::Model::set_theta (double t0, double t1, double t2) [protected]
Definition at line 166 of file model.cpp.
References m_theta.
Referenced by init_pos(), and Model().
set_theta_spd()
void stp::Model::set_theta_spd (double t0, double t1, double t2) [protected]
Definition at line 173 of file model.cpp.
References m_theta_spd.
Referenced by init_pos(), and Model().
Member Data Documentation
_alphaI
double stp::Model::_alphaI[6] [protected]
Definition at line 81 of file model.hpp.
Referenced by init_pos().
_d2
double stp::Model::_d2[NB_LEGS] [protected]
Distance between the axe of the motors and the coresponding legs-platform articulation.
Definition at line 52 of file model.hpp.
Referenced by new_pos().
m_a
double stp::Model::m_a [protected]
Definition at line 49 of file model.hpp.
Referenced by Model(), new_pos(), and stp::Gnuplot_sim::update_draw().
m_A
double stp::Model::m_A[NB_LEGS][3] [protected]
Position of the arms-legs articulation in the base B0.
Definition at line 64 of file model.hpp.
Referenced by stp::Gnuplot_sim::update_draw().
m_a2
double stp::Model::m_a2 [protected]
Size of the motors' arms.
Definition at line 49 of file model.hpp.
Referenced by init_pos(), Model(), and new_pos().
m_alpha
double stp::Model::m_alpha[NB_LEGS] [protected]
Angular postion of the rotor.
Definition at line 68 of file model.hpp.
Referenced by init_pos(), new_pos(), stp::Gnuplot_sim::new_pos(), stp::Platform::new_pos(), stp::Gnuplot_sim::update_draw(), and stp::Platform::update_platform().
m_alpha_spd
double stp::Model::m_alpha_spd[6] [protected]
Rotation speed of the motors.
Definition at line 79 of file model.hpp.
Referenced by Model().
m_B
double stp::Model::m_B[NB_LEGS][3] [protected]
Position of the motors-arms articulation in the base B0.
Definition at line 62 of file model.hpp.
Referenced by stp::Gnuplot_sim::draw(), stp::Gnuplot_sim::Gnuplot_sim(), init_pos(), Model(), new_pos(), and stp::Gnuplot_sim::update_draw().
m_beta
double stp::Model::m_beta[NB_LEGS] [protected]
Orientation of the motor on the base.
Definition at line 67 of file model.hpp.
Referenced by Model(), new_pos(), and stp::Gnuplot_sim::update_draw().
m_gamma
double stp::Model::m_gamma[2][NB_LEGS] [protected]
Angular position of the motor on the base
Definition at line 70 of file model.hpp.
Referenced by Model().
m_l
double stp::Model::m_l [protected]
Definition at line 50 of file model.hpp.
Referenced by Model().
m_l2
double stp::Model::m_l2 [protected]
Size of the legs.
Definition at line 50 of file model.hpp.
Referenced by init_pos(), Model(), and new_pos().
m_P
double stp::Model::m_P[NB_LEGS][3] [protected]
Position of the legs-platform articulation in the base B0.
Definition at line 56 of file model.hpp.
Referenced by new_pos(), and stp::Gnuplot_sim::update_draw().
m_P1
double stp::Model::m_P1[NB_LEGS][3] [protected]
Position of the legs-platform articulation in the base B1.
Definition at line 59 of file model.hpp.
Referenced by init_pos(), Model(), and new_pos().
m_parity
double stp::Model::m_parity[NB_LEGS] [protected]
Use to represent the side of the motor arm.
Definition at line 66 of file model.hpp.
Referenced by Model().
m_R
double stp::Model::m_R[3][3] [protected]
Matrix of rotation.
Definition at line 74 of file model.hpp.
Referenced by compute_R(), and new_pos().
m_radius
double stp::Model::m_radius[2] [protected]
Definition at line 47 of file model.hpp.
Referenced by stp::Gnuplot_sim::draw(), and Model().
m_T
double stp::Model::m_T[3] [protected]
Postion of the center of the platform.
Definition at line 72 of file model.hpp.
Referenced by get_T(), init_pos(), new_pos(), and set_T().
m_T_spd
double stp::Model::m_T_spd[3] [protected]
Velocity of the platform.
Definition at line 77 of file model.hpp.
Referenced by set_T_spd().
m_theta
double stp::Model::m_theta[3] [protected]
Orientation of the platform.
Definition at line 73 of file model.hpp.
Referenced by compute_R(), get_theta(), init_pos(), new_pos(), and set_theta().
m_theta_spd
double stp::Model::m_theta_spd[3] [protected]
Rotation speed of the platform.
Definition at line 78 of file model.hpp.
Referenced by set_theta_spd().
m_trig
double stp::Model::m_trig[6] [protected]
(cos(theta_i),sin(theta_i))
Definition at line 75 of file model.hpp.
Referenced by compute_R().
The documentation for this class was generated from the following files:
include/model.hpp
src/model.cpp