gnuplotio::Gnuplot Class Reference
#include <gnuplot-iostream.h>
Public Member Functions
Gnuplot (const std::string &_cmd=``)
Gnuplot (FILE *_fh)
~Gnuplot ()
void clearTmpfiles ()
template<typename T , typename OrganizationMode >
Gnuplot & send (const T &arg, OrganizationMode)
template<typename T , typename OrganizationMode >
Gnuplot & sendBinary (const T &arg, OrganizationMode)
template<typename T , typename OrganizationMode >
std::string binfmt (const T &arg, const std::string &arr_or_rec, OrganizationMode)
template<typename T , typename OrganizationMode >
std::string file (const T &arg, std::string filename, OrganizationMode)
template<typename T , typename OrganizationMode >
std::string binaryFile (const T &arg, std::string filename, const std::string &arr_or_rec, OrganizationMode)
template<typename T >
Gnuplot GNUPLOT_DEPRECATE (`use send1d or send2d`) &send(const T &arg)
template<typename T >
std::string GNUPLOT_DEPRECATE (`use binfmt1d or binfmt2d`) binfmt(const T &arg
Public Attributes
std::string const std::string & arr_or_rec
std::vector< int > tmp_files
bool debug_messages
Private Member Functions
Gnuplot (const Gnuplot &)
const Gnuplot & operator= (const Gnuplot &)
void do_flush ()
std::string make_tmpfile ()
Static Private Member Functions
static std::string get_default_cmd ()
static FileHandleWrapper open_cmdline (const std::string &in)
Additional Inherited Members
Detailed Description
Definition at line 1551 of file gnuplot-iostream.h.
Constructor & Destructor Documentation
Gnuplot() [1/3]
gnuplotio::Gnuplot::Gnuplot (const std::string & _cmd = ``) [inline], [explicit]
Definition at line 1588 of file gnuplot-iostream.h.
Gnuplot() [2/3]
gnuplotio::Gnuplot::Gnuplot (FILE * _fh) [inline], [explicit]
Definition at line 1605 of file gnuplot-iostream.h.
Gnuplot() [3/3]
gnuplotio::Gnuplot::Gnuplot (const Gnuplot &) [private]
 Gnuplot()
gnuplotio::Gnuplot::~Gnuplot () [inline]
Definition at line 1628 of file gnuplot-iostream.h.
Member Function Documentation
binaryFile()
template<typename T , typename OrganizationMode >
std::string gnuplotio::Gnuplot::binaryFile (const T & arg, std::string filename, const std::string & arr_or_rec, OrganizationMode) [inline]
Definition at line 1726 of file gnuplot-iostream.h.
References gnuplotio::top_level_array_sender().
binfmt()
template<typename T , typename OrganizationMode >
std::string gnuplotio::Gnuplot::binfmt (const T & arg, const std::string & arr_or_rec, OrganizationMode) [inline]
Definition at line 1691 of file gnuplot-iostream.h.
References gnuplotio::top_level_array_sender().
clearTmpfiles()
void gnuplotio::Gnuplot::clearTmpfiles () [inline]
Definition at line 1645 of file gnuplot-iostream.h.
do_flush()
void gnuplotio::Gnuplot::do_flush () [inline], [private]
Definition at line 1651 of file gnuplot-iostream.h.
file()
template<typename T , typename OrganizationMode >
std::string gnuplotio::Gnuplot::file (const T & arg, std::string filename, OrganizationMode) [inline]
Definition at line 1711 of file gnuplot-iostream.h.
References gnuplotio::top_level_array_sender().
get_default_cmd()
static std::string gnuplotio::Gnuplot::get_default_cmd () [inline], [static], [private]
Definition at line 1559 of file gnuplot-iostream.h.
References GNUPLOT_DEFAULT_COMMAND, GNUPLOT_MSVC_WARNING_4996_POP, and GNUPLOT_MSVC_WARNING_4996_PUSH.
GNUPLOT_DEPRECATE() [1/2]
template<typename T >
Gnuplot gnuplotio::Gnuplot::GNUPLOT_DEPRECATE (`use send1d or send2d`) const & [inline]
Definition at line 1744 of file gnuplot-iostream.h.
GNUPLOT_DEPRECATE() [2/2]
template<typename T >
std::string gnuplotio::Gnuplot::GNUPLOT_DEPRECATE (`use binfmt1d or binfmt2d`) const &
make_tmpfile()
std::string gnuplotio::Gnuplot::make_tmpfile () [inline], [private]
Definition at line 1656 of file gnuplot-iostream.h.
open_cmdline()
static FileHandleWrapper gnuplotio::Gnuplot::open_cmdline (const std::string & in) [inline], [static], [private]
Definition at line 1570 of file gnuplot-iostream.h.
References GNUPLOT_MSVC_WARNING_4996_POP, GNUPLOT_MSVC_WARNING_4996_PUSH, and GNUPLOT_POPEN.
operator=()
const Gnuplot& gnuplotio::Gnuplot::operator= (const Gnuplot &) [private]
send()
template<typename T , typename OrganizationMode >
Gnuplot& gnuplotio::Gnuplot::send (const T & arg, OrganizationMode) [inline]
Definition at line 1676 of file gnuplot-iostream.h.
References gnuplotio::top_level_array_sender().
sendBinary()
template<typename T , typename OrganizationMode >
Gnuplot& gnuplotio::Gnuplot::sendBinary (const T & arg, OrganizationMode) [inline]
Definition at line 1684 of file gnuplot-iostream.h.
References gnuplotio::top_level_array_sender().
Member Data Documentation
arr_or_rec
std::string const std::string& gnuplotio::Gnuplot::arr_or_rec
Definition at line 1747 of file gnuplot-iostream.h.
debug_messages
bool gnuplotio::Gnuplot::debug_messages
Definition at line 1848 of file gnuplot-iostream.h.
tmp_files
std::vector<int> gnuplotio::Gnuplot::tmp_files
Definition at line 1844 of file gnuplot-iostream.h.
The documentation for this class was generated from the following file:
include/gnuplot-iostream.h