/home/adev/Documents/STECH/stewart_platform/lib/lxm32/src/main.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <cstdint>
#include <net/if.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <linux/can.h>
#include <linux/can/raw.h>
#include `CANopen_lxm32.h`
#include `joystick.h`
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 22 of file main.cpp.
References CANopen::Driver::get_position(), CANopen::Driver::profilePosition_mode(), CANopen::Driver::set_position(), CANopen::Driver::set_position_offset(), and CANopen::Driver::start().