CANopen::Parameter Struct Reference
Object from the object dictionary of a remote CANopen device.
#include <parameter.h>
Public Types
enum PDOFunctionCode : uint32_t {
PDO1Transmit = Message::PDO1Transmit,
PDO1Receive = Message::PDO1Receive,
PDO2Transmit = Message::PDO2Transmit,
PDO2Receive = Message::PDO2Receive,
PDO3Transmit = Message::PDO3Transmit,
PDO3Receive = Message::PDO3Receive,
PDO4Transmit = Message::PDO4Transmit,
PDO4Receive = Message::PDO4Receive
 }
PDO Function code.
typedef void(* param_cb_t) (Parameter *)
Public Member Functions
template<typename T >
Parameter (std::string name_, T val, uint16_t index_, uint8_t subindex_, param_cb_t cb=nullptr)
Parameter Constructor.
template<typename T >
Parameter (std::string name_, T val, uint32_t index__sub, param_cb_t cb=nullptr)
Parameter Constructor.
void link_to_pdo (PDOFunctionCode fn, int8_t slot)
link_to_pdo Links a paramet to a PDO message
template<typename T >
bool set (T val, bool force_update=false, bool received_data=false)
sets Set the value of a parameter.
bool operator= (int8_t val)
Sets the value of the parameter.
bool operator= (int16_t val)
Sets the value of the parameter.
bool operator= (int32_t val)
Sets the value of the parameter.
bool operator= (uint8_t val)
Sets the value of the parameter.
bool operator= (uint16_t val)
Sets the value of the parameter.
bool operator= (uint32_t val)
Sets the value of the parameter.
template<typename T >
T get ()
gets Returns the value (with a type T coherent with the data size)
operator int8_t ()
operator int8_t Returns the value as an int8_t
operator int16_t ()
operator int16_t Returns the value as an int16_t
operator int32_t ()
operator int32_t Returns the value as an int32_t
operator uint8_t ()
operator uint8_t Returns the value as an uint8_t
operator uint16_t ()
operator uint16_t Returns the value as an uint16_t
operator uint32_t ()
operator uint32_t Returns the value as an uint32_t
bool from_payload (Payload &p, int slot=0, bool received_data=true)
from_payload Sets the value of the parameters with the data of a payload.
bool has_been_sent ()
has_been_sent Returns the sending flag.
void callback ()
callback Execute the parameter callback (If not null)
Payload payload (bool *should_be_sent=nullptr)
payload Returns a payload filled with the parameter data.
Public Attributes
size_t size = 0
std::string name
uint16_t index = 0
uint8_t subindex = 0
PDOFunctionCode pdo_fn
int8_t pdo_slot = -1
std::atomic_flag sdo_flag
Detailed Description
Object from the object dictionary of a remote CANopen device.
Definition at line 24 of file parameter.h.
Member Typedef Documentation
param_cb_t
typedef void(* CANopen::Parameter::param_cb_t) (Parameter *)
Parameter Callback function type
Definition at line 29 of file parameter.h.
Constructor & Destructor Documentation
Parameter() [1/2]
template<typename T >
CANopen::Parameter::Parameter (std::string name_, T val, uint16_t index_, uint8_t subindex_, param_cb_t cb = nullptr) [inline]
Parameter Constructor.
Parameters
name_ Name of the parameter.
val Value to store in the parameter (the type will be used to fixed the data size)
index_ Index of the object in the object dictionary of the device.
subindex_ Subindex of the object in the object dictionary of the device.
cb [facultative] The address of a callback function that will be called each time the parameter is updated by the device.
Definition at line 56 of file parameter.h.
Parameter() [2/2]
template<typename T >
CANopen::Parameter::Parameter (std::string name_, T val, uint32_t index__sub, param_cb_t cb = nullptr) [inline]
Parameter Constructor.
Parameters
name_ Name of the parameter.
val Value to store in the parameter (the type will be used to fixed the data size)
index__sub Index and subindex of the object in the object dictionary of the device. (in the format index__sub)
cb [facultative] The address of a callback function that will be called each time the parameter is updated by the device.
Definition at line 73 of file parameter.h.
Member Function Documentation
from_payload()
bool CANopen::Parameter::from_payload (Payload & p, int slot = 0, bool received_data = true)
from_payload Sets the value of the parameters with the data of a payload.
Parameters
p Payload to store in the parameter
slot Index in the payload array where the parameter data is
received_data If set the data is processed as a receied data (no sending flag raised)
Returns
True if the parameter value has been changed.
Definition at line 14 of file parameter.cpp.
References CANopen::Payload::value().
get()
template<typename T >
T CANopen::Parameter::get () [inline]
gets Returns the value (with a type T coherent with the data size)
Returns
The value of the parameter.
Definition at line 164 of file parameter.h.
has_been_sent()
bool CANopen::Parameter::has_been_sent () [inline]
has_been_sent Returns the sending flag.
Returns
The sending flag.
Definition at line 214 of file parameter.h.
link_to_pdo()
void CANopen::Parameter::link_to_pdo (PDOFunctionCode fn, int8_t slot)
link_to_pdo Links a paramet to a PDO message
Parameters
fn The function code of the PDO
slot The index of the parameter data inside the PDO Message Payload
Definition at line 4 of file parameter.cpp.
Referenced by CANopen::Driver::map_PDO().
operator=() [1/6]
bool CANopen::Parameter::operator= (int16_t val) [inline]
Sets the value of the parameter.
Parameters
val New int16_t value to set
Returns
True if the parameter value has been changed.
Definition at line 128 of file parameter.h.
operator=() [2/6]
bool CANopen::Parameter::operator= (int32_t val) [inline]
Sets the value of the parameter.
Parameters
val New int32_t value to set
Returns
True if the parameter value has been changed.
Definition at line 135 of file parameter.h.
operator=() [3/6]
bool CANopen::Parameter::operator= (int8_t val) [inline]
Sets the value of the parameter.
Parameters
val New int8_t value to set
Returns
True if the parameter value has been changed.
Definition at line 121 of file parameter.h.
operator=() [4/6]
bool CANopen::Parameter::operator= (uint16_t val) [inline]
Sets the value of the parameter.
Parameters
val New uint16_t value to set
Returns
True if the parameter value has been changed.
Definition at line 149 of file parameter.h.
operator=() [5/6]
bool CANopen::Parameter::operator= (uint32_t val) [inline]
Sets the value of the parameter.
Parameters
val New uint32_t value to set
Returns
True if the parameter value has been changed.
Definition at line 156 of file parameter.h.
operator=() [6/6]
bool CANopen::Parameter::operator= (uint8_t val) [inline]
Sets the value of the parameter.
Parameters
val New uint8_t value to set
Returns
True if the parameter value has been changed.
Definition at line 142 of file parameter.h.
payload()
CANopen::Payload CANopen::Parameter::payload (bool * should_be_sent = nullptr)
payload Returns a payload filled with the parameter data.
Parameters
should_be_sent If a boolean pointer is passed the sending flag is stored in the booled and then cleared.
Returns
A payload filled with the parameter data.
Definition at line 29 of file parameter.cpp.
Referenced by CANopen::Driver::send().
set()
template<typename T >
bool CANopen::Parameter::set (T val, bool force_update = false, bool received_data = false) [inline]
sets Set the value of a parameter.
Parameters
val The value to set. (the type has to be coherent with the parameter data size)
force_update If set the value of the Parameter is set even idf the previous value has not been sent yet to the remote device.
received_data Has to be set to True if the data being set come from the remote device (so the sending flag will not be raised)
Returns
True if the parameter value has been changed.
Definition at line 96 of file parameter.h.
The documentation for this struct was generated from the following files:
parameter.h
parameter.cpp