gnuplotio::BinfmtSender< T, Enable > Struct Template Reference
#include <gnuplot-iostream.h>
Public Member Functions
GNUPLOT_STATIC_ASSERT_MSG ((sizeof(T)==0), `BinfmtSender class not specialized for this type`)
Static Public Member Functions
static void send (std::ostream &)
Detailed Description
template<typename T, typename Enable = void>
struct gnuplotio::BinfmtSender< T, Enable >
Definition at line 459 of file gnuplot-iostream.h.
Member Function Documentation
GNUPLOT_STATIC_ASSERT_MSG()
template<typename T , typename Enable = void>
gnuplotio::BinfmtSender< T, Enable >::GNUPLOT_STATIC_ASSERT_MSG ((sizeof(T)==0) , `BinfmtSender< T, Enable > class not specialized for this type`)
send()
template<typename T , typename Enable = void>
static void gnuplotio::BinfmtSender< T, Enable >::send (std::ostream &) [static]
Referenced by gnuplotio::BinfmtSender< std::pair< T, U > >::send(), gnuplotio::BinfmtSender< std::complex< T > >::send(), gnuplotio::BinfmtSender< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, boost::mpl::not_< is_boost_tuple_nulltype< typename T::tail_type > > > >::type >::send(), gnuplotio::BinfmtSender< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, is_boost_tuple_nulltype< typename T::tail_type > > >::type >::send(), and gnuplotio::send_scalar().
The documentation for this struct was generated from the following file:
/home/adev/Documents/STECH/stewart_platform/include/gnuplot-iostream.h