gnuplotio::TextSender< T, Enable > Struct Template Reference
#include <gnuplot-iostream.h>
Static Public Member Functions
static void send (std::ostream &stream, const T &v)
Detailed Description
template<typename T, typename Enable = void>
struct gnuplotio::TextSender< T, Enable >
Definition at line 433 of file gnuplot-iostream.h.
Member Function Documentation
send()
template<typename T , typename Enable = void>
static void gnuplotio::TextSender< T, Enable >::send (std::ostream & stream, const T & v) [inline], [static]
Definition at line 434 of file gnuplot-iostream.h.
Referenced by gnuplotio::TextSender< std::pair< T, U > >::send(), gnuplotio::TextSender< std::complex< T > >::send(), gnuplotio::TextSender< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, boost::mpl::not_< is_boost_tuple_nulltype< typename T::tail_type > > > >::type >::send(), gnuplotio::TextSender< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, is_boost_tuple_nulltype< typename T::tail_type > > >::type >::send(), and gnuplotio::send_scalar().
The documentation for this struct was generated from the following file:
/home/adev/Documents/STECH/stewart_platform/include/gnuplot-iostream.h